#ifndef ACIM_DEVICE_EVENTS_H
#define ACIM_DEVICE_EVENTS_H

#define ACIM_DEVICE_EVENT_DICTIONARY_VERSION 1u

#define ACIM_EVENT_COMMAND_DISPATCH 1u
#define ACIM_EVENT_DESCRIPTOR_VALIDATE 2u
#define ACIM_EVENT_WEIGHT_PROGRAM 3u
#define ACIM_EVENT_CALIBRATION 4u
#define ACIM_EVENT_INPUT_DMA 5u
#define ACIM_EVENT_INPUT_DRIVE_DAC 6u
#define ACIM_EVENT_ARRAY_SETTLE_MVM 7u
#define ACIM_EVENT_ADC_CONVERT 8u
#define ACIM_EVENT_DIGITAL_PARTIAL_SUM 9u
#define ACIM_EVENT_OUTPUT_DMA 10u
#define ACIM_EVENT_ADC_SATURATION_COUNT 64u
#define ACIM_EVENT_RETRY_COUNT 65u
#define ACIM_EVENT_REMAP_COUNT 66u
#define ACIM_EVENT_CONVERTER_BUSY_CYCLES 67u

#endif
